# Generated by Django 2.1.9 on 2019-06-17 17:49

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rmanager', '0003_auto_20190608_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='denorm_chart',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
    ]
